#!/usr/bin/env bash
#
# Copyright 2017-2020 AVSystem <avsystem@avsystem.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

./devconfig \
        --c-flags '-Os -DNDEBUG -flto' \
        --without-dtls \
        -D CMAKE_EXE_LINKER_FLAGS='-flto' \
        -D CMAKE_SHARED_LINKED_FLAGS='-flto' \
        -D CMAKE_AR="$(which gcc-ar)" \
        -D CMAKE_RANLIB="$(which gcc-ranlib)" \
        -D WITH_LIBRARY_SHARED=OFF \
        -D AVS_LOG_WITH_TRACE=OFF \
        "$@"
