/*
 * Copyright 2023-2024 AVSystem <avsystem@avsystem.com>
 * AVSystem Anjay LwM2M SDK
 * All rights reserved.
 *
 * Licensed under the AVSystem-5-clause License.
 * See the attached LICENSE file for details.
 */

#ifndef ANJAY_LITE_CONFIG_H
#define ANJAY_LITE_CONFIG_H

/**
 * ANJAY_SERVERS
 */
#ifndef ANJAY_LITE_ALLOWED_SERVERS_NUMBER
#    define ANJAY_LITE_ALLOWED_SERVERS_NUMBER 1
#endif // ANJAY_LITE_ALLOWED_SERVERS_NUMBER

#ifndef ANJAY_LITE_MSG_BUFF_SIZE
#    define ANJAY_LITE_MSG_BUFF_SIZE 1500
#endif // ANJAY_LITE_MSG_BUFF_SIZE

#ifndef ANJAY_LITE_RECONNECTION_TIMEOUT_MS
#    define ANJAY_LITE_RECONNECTION_TIMEOUT_MS 5000
#endif // ANJAY_LITE_RECONNECTION_TIMEOUT_MS

#ifndef ANJAY_LITE_RESPONSE_TIMEOUT_MS
#    define ANJAY_LITE_RESPONSE_TIMEOUT_MS 20000
#endif // ANJAY_LITE_RECONNECTION_TIMEOUT_MS

#ifndef ANJAY_LITE_SERVERS_REGISTER_PATH_STR_LEN
#    define ANJAY_LITE_SERVERS_REGISTER_PATH_STR_LEN 30
#endif // ANJAY_LITE_SERVERS_REGISTER_PATH_STR_LEN

/**
 * ANJAY_DM
 */
#ifndef ANJAY_LITE_ALLOWED_OBJECT_NUMBER
#    define ANJAY_LITE_ALLOWED_OBJECT_NUMBER 6
#endif // ANJAY_LITE_ALLOWED_OBJECT_NUMBER

#ifndef ANJAY_LITE_PAYLOAD_BUFF_SIZE
#    define ANJAY_LITE_PAYLOAD_BUFF_SIZE (512)
#endif // ANJAY_LITE_PAYLOAD_BUFF_SIZE

#endif // ANJAY_LITE_CONFIG_H
