# Copyright 2017-2021 AVSystem <avsystem@avsystem.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Coverity
on:
  push:
    branches: [master]
jobs:
  coverity:
    runs-on: ubuntu-latest
    container: avsystemembedded/anjay-travis:ubuntu-16.04
    env:
      # NOTE: These need to be configured in GitHub Actions GUI
      COVERITY_EMAIL: ${{ secrets.COVERITY_EMAIL }}
      COVERITY_SCAN_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
    steps:
      # NOTE: v2 requires Git 2.18 for submodules, it's not present in the image
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - run: |
          mkdir -p coverity_tool
          bash -c 'cd coverity_tool && \
              wget https://scan.coverity.com/download/linux64 --post-data "token=$COVERITY_SCAN_TOKEN&project=AVSystem%2FAnjay" -O coverity_tool.tgz && \
              tar xf coverity_tool.tgz'
      - run: ./devconfig --without-analysis -DWITH_URL_CHECK=OFF
      - run: env LC_ALL=C.UTF-8 ./coverity_tool/cov-analysis*/bin/cov-build --dir cov-int make
      - run: tar zcf cov-int.tgz cov-int
      - run: |
          curl --form "token=$COVERITY_SCAN_TOKEN" \
               --form "email=$COVERITY_EMAIL" \
               --form file=@cov-int.tgz \
               --form version=$(git rev-parse HEAD) \
               --form description="" \
               https://scan.coverity.com/builds?project=AVSystem%2FAnjay
