# Copyright 2017-2025 AVSystem <avsystem@avsystem.com>
# AVSystem Anjay LwM2M SDK
# All rights reserved.
#
# Licensed under the AVSystem-5-clause License.
# See the attached LICENSE file for details.

name: Coverity
on:
  push:
    branches: [master]
jobs:
  coverity:
    runs-on: ubuntu-latest
    container: avsystemembedded/anjay-travis:ubuntu-22.04-1.1
    env:
      # NOTE: These need to be configured in GitHub Actions GUI
      COVERITY_EMAIL: ${{ secrets.COVERITY_EMAIL }}
      COVERITY_SCAN_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
    steps:
      # NOTE: workaround for https://github.com/actions/checkout/issues/760
      - run: git config --global safe.directory '*'
      # NOTE: v2 requires Git 2.18 for submodules, it's not present in the image
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - run: |
          mkdir -p coverity_tool
          bash -c 'cd coverity_tool && \
              wget https://scan.coverity.com/download/linux64 --post-data "token=$COVERITY_SCAN_TOKEN&project=AVSystem%2FAnjay" -O coverity_tool.tgz && \
              tar xf coverity_tool.tgz'
      - run: ./devconfig --without-analysis -DWITH_URL_CHECK=OFF -DWITH_NESTED_FUNCTION_MUTEX_LOCKS=OFF -DWITH_IPV6=OFF
      - run: env LC_ALL=C.UTF-8 ./coverity_tool/cov-analysis*/bin/cov-build --dir cov-int make
      - run: tar zcf cov-int.tgz cov-int
      - run: |
          curl --form "token=$COVERITY_SCAN_TOKEN" \
               --form "email=$COVERITY_EMAIL" \
               --form file=@cov-int.tgz \
               --form version=$(git rev-parse HEAD) \
               --form description="" \
               https://scan.coverity.com/builds?project=AVSystem%2FAnjay
